name: qtank_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons:
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  go_router: ^4.1.0
  flutter_riverpod: ^1.0.4
  logger: ^1.1.0
  intl: ^0.17.0
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/tank-solo.png"


flutter:

  uses-material-design: true
  assets:
    - assets/tank-solo.png
    - assets/tank-only.png
    - assets/tank-wide.png
    - assets/tank-only-removebg.png
    - assets/dammy_icon_1.png
    - assets/dammy_icon_2.png
    - assets/dammy_icon_3.png
    - assets/dammy_icon_4.png

flutter_native_splash:
  image: assets/tank-only-removebg.png
  color: "ffffff"
  
  web: false